name: Build Check

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build-check:
    name: Quick Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Test executable build
        run: bun run build:executable

      - name: Test build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build output not found!"
            exit 1
          fi
          if [ ! -f "pendant" ]; then
            echo "Executable not found!"
            exit 1
          fi
          echo "Build successful!"
