name: Cross-Platform Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        bun-version: [latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run type checking
        run: bun run type-check

      - name: Test platform-specific paths
        shell: bash
        run: |
          echo "Testing platform-specific behavior on ${{ matrix.os }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Windows-specific tests"
            # Verify Windows path handling
            bun test test/constants/application-paths.test.ts --verbose
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "macOS-specific tests"
            # Verify macOS path handling
            bun test test/constants/application-paths.test.ts --verbose
          else
            echo "Linux-specific tests"
            # Verify Linux path handling
            bun test test/constants/application-paths.test.ts --verbose
          fi
