name: Cross-Platform Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        bun-version: [latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run type checking
        run: bun run type-check

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Upload coverage to Codecov (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

      - name: Test platform-specific paths
        shell: bash
        run: |
          echo "Testing platform-specific behavior on ${{ matrix.os }}"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "Windows-specific tests"
            # Verify Windows path handling
            bun test test/constants/application-paths.test.ts --verbose
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "macOS-specific tests"
            # Verify macOS path handling
            bun test test/constants/application-paths.test.ts --verbose
          else
            echo "Linux-specific tests"
            # Verify Linux path handling
            bun test test/constants/application-paths.test.ts --verbose
          fi

  coverage-check:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate coverage report
        run: bun test --coverage

      - name: Coverage check
        run: |
          echo "Checking if coverage meets minimum threshold..."
          # Extract coverage percentage and check if >= 95%
          coverage=$(bun test --coverage 2>&1 | grep "All files" | awk '{print $4}' | sed 's/%//')
          echo "Current coverage: ${coverage}%"
          if (( $(echo "$coverage >= 95" | bc -l) )); then
            echo "✅ Coverage meets minimum requirement (≥95%)"
          else
            echo "❌ Coverage below minimum requirement (${coverage}% < 95%)"
            exit 1
          fi
