name: Publish to NPM

# This workflow requires an NPM_TOKEN secret to be configured
# Go to: https://github.com/howmanysmall/pendant/settings/secrets/actions
# Create a secret named: NPM_TOKEN

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: read
  id-token: write # for npm provenance

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || inputs.tag }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js for NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build output not found!"
            exit 1
          fi
          echo "Build verified successfully"

      - name: Check NPM token
        id: check-token
        run: |
          if [ -n "$NPM_TOKEN" ]; then
            echo "✅ NPM_TOKEN is configured"
            echo "has-token=true" >> $GITHUB_OUTPUT
          else
            echo "❌ NPM_TOKEN secret is not set. Please add it to repository secrets."
            echo "Go to: https://github.com/howmanysmall/pendant/settings/secrets/actions"
            echo "has-token=false" >> $GITHUB_OUTPUT
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        if: steps.check-token.outputs.has-token == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
