name: Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Windows x86-64
          - os: windows-latest
            platform: windows-x64
            target: bun-windows-x64
            extension: .exe
          # macOS x86-64
          - os: macos-13
            platform: macos-x64
            target: bun-darwin-x64
            extension: ''
          # macOS ARM64
          - os: macos-latest
            platform: macos-arm64
            target: bun-darwin-arm64
            extension: ''
          # Ubuntu x86-64
          - os: ubuntu-latest
            platform: linux-x64
            target: bun-linux-x64
            extension: ''
          # Ubuntu ARM64 (cross-compile)
          - os: ubuntu-latest
            platform: linux-arm64
            target: bun-linux-arm64
            extension: ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build project
        run: bun run build

      - name: Create standalone executable
        run: |
          if [ "${{ matrix.platform }}" = "linux-arm64" ]; then
            # For ARM64 Linux, we need to cross-compile
            bun build ./dist --compile --production --target=${{ matrix.target }} --outfile=pendant-${{ matrix.platform }}${{ matrix.extension }} --minify
          else
            bun build ./dist --compile --production --target=bun --outfile=pendant-${{ matrix.platform }}${{ matrix.extension }} --minify
          fi
        shell: bash

      - name: Create archive
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a pendant-${{ matrix.platform }}.zip pendant-${{ matrix.platform }}${{ matrix.extension }}
          else
            tar -czf pendant-${{ matrix.platform }}.tar.gz pendant-${{ matrix.platform }}${{ matrix.extension }}
          fi
        shell: bash

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: pendant-${{ matrix.platform }}${{ matrix.extension == '.exe' && '.zip' || '.tar.gz' }}

      - name: Upload artifacts (for workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: pendant-${{ matrix.platform }}
          path: pendant-${{ matrix.platform }}${{ matrix.extension == '.exe' && '.zip' || '.tar.gz' }}
          retention-days: 30
